import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/nav";

export const metadata: Metadata = {
  title: "Kenneth's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-black text-white p-4">
        <Navbar />
        {children}
        <footer className=" md:text-xl p-4">© 2024 Kenneth Manuel</footer>
      </body>
    </html>
  );
}
